server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /gateway
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
    customer-by-service:
      path: /data-service/**
      serviceId: DATA-SERVICE
    static:
      path: /static/**


spring:
  application:
    name: zuul-gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  file: zuul-console.log
